admin_index:
    path: /
    defaults: { _controller: PhotoBundle:Admin/Admin:index }

admin_photos:
    path: /photos/{albumUrl}
    defaults: { _controller: PhotoBundle:Admin/Photo:index, albumUrl: svadba }

admin_blog:
    path: /blog/
    defaults: { _controller: PhotoBundle:Admin/Admin:index }