admin_index:
    path: /
    defaults: { _controller: PhotoBundle:Admin:index }

admin_photos:
    path: /photos/{albumName}
    defaults: { _controller: PhotoBundle:Admin:index, albumName: svadba }

admin_blog:
    path: /blog/
    defaults: { _controller: PhotoBundle:Admin:index }