<?php

namespace PhotoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    public function getAllActualAlbums() {
        return $this->findBy(['enabled' => true]);
    }
}
