<?php

namespace PhotoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use PhotoBundle\Entity\Album;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    /**
     * @return Album[]
     */
    public function getAllActualAlbums() {
        return $this->findBy(['enabled' => true]);
    }

    /**
     * @return array
     */
    public function getAllAlbumURLs() {
        $albums = $this->findBy(['enabled' => true]);
        $urls = array();
        /** @var Album $album */
        foreach($albums as $album) {
            $urls[] = $album->getUrl();
        }

        return $urls;
    }

    /**
     * @param $albumURL string
     * @return Album|null
     */
    public function getAlbumByURL($albumURL) {
        return $this->findOneBy(['url' => $albumURL]);
    }
}
