<?php

namespace PhotoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use PhotoBundle\Entity\Album;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    /**
     * Получение списка альбомов, у которых sortIndex больше переданного
     *
     * @param $sortIndex integer
     * @return Album[]
     */
    public function getAlbumsWithMoreSortIndex($sortIndex) {
        return $this->createQueryBuilder('al')
            ->where('al.sortIndex > :sortIndex')
            ->setParameter('sortIndex', $sortIndex)
            ->getQuery()
            ->getResult();
    }

    /**
     * Получение отсортированного списка включенных альбомов
     *
     * @return Album[]
     */
    public function getAllActualAlbums() {
        return $this->findBy(['enabled' => true], ['sortIndex' => 'ASC']);
    }

    /**
     * Получение альбома по его URL
     *
     * @param $albumURL string
     * @return Album|null
     */
    public function getAlbumByURL($albumURL) {
        return $this->findOneBy(['url' => $albumURL]);
    }
}
