<?php

namespace PhotoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getPosts($start, $limit) {
        return $this->findBy(array('enabled' => true), array('dateCreate' => 'DESC'), $limit, $start);
    }

    public function getLastPost() {
        return $this->findOneBy(array('enabled' => true), array('dateCreate' => 'DESC'));
    }
}
