admin_index:
    path: /
    defaults: { _controller: PhotoBundle:Admin/Admin:index }

photo_admin_album:
    resource: "@PhotoBundle/Resources/config/routing/admin/albums.yml"
    prefix:   /albums/

photo_admin_photos:
    resource: "@PhotoBundle/Resources/config/routing/admin/photos.yml"
    prefix:   /photos/


admin_blog:
    path: /blog/
    defaults: { _controller: PhotoBundle:Admin/Admin:index }