admin_album:
    path:     /
    defaults: { _controller: "PhotoBundle:Album:index" }

admin_album_enabled:
    path:     /{albumId}/enabled/
    defaults: { _controller: "PhotoBundle:Album:enabled" }

admin_album_disabled:
    path:     /{albumId}/disabled/
    defaults: { _controller: "PhotoBundle:Album:disabled" }

admin_album_show:
    path:     /{id}/show
    defaults: { _controller: "PhotoBundle:Album:show" }

admin_album_new:
    path:     /new
    defaults: { _controller: "PhotoBundle:Album:new" }

admin_album_create:
    path:     /create
    defaults: { _controller: "PhotoBundle:Album:create" }
    methods:  POST

admin_album_edit:
    path:     /{id}/edit
    defaults: { _controller: "PhotoBundle:Album:edit" }

admin_album_update:
    path:     /{id}/update
    defaults: { _controller: "PhotoBundle:Album:update" }
    methods:  [POST, PUT]

admin_album_delete:
    path:     /{id}/delete
    defaults: { _controller: "PhotoBundle:Album:delete" }
    methods:  [POST, DELETE]
