photo_homepage:
    path: /
    defaults: { _controller: PhotoBundle:Photo:index }

photo_about:
    path: /about/
    defaults: { _controller: PhotoBundle:Photo:about }

photo_albums:
    path: /albums/{albumURL}/
    defaults: { _controller: PhotoBundle:Photo:albums, albumUrl: svadba }

photo_price:
    path: /price/{pricePage}/
    defaults: { _controller: PhotoBundle:Photo:price }

photo_blog:
    path: /blog/{page}
    defaults: { _controller: PhotoBundle:Photo:blog, page: 1 }

photo_blog_article:
    path: /article/{id}
    defaults: { _controller: PhotoBundle:Photo:article }

photo_contacts:
    path: /contacts/
    defaults: { _controller: PhotoBundle:Photo:contacts }

photo_rent:
    path: /arenda/
    defaults: { _controller: PhotoBundle:Photo:rent }