photo_admin_album:
    resource: "@PhotoBundle/Resources/config/routing/album.yml"
    prefix:   /admin/albums/

photo_view:
    resource: "@PhotoBundle/Resources/config/routing/view.yml"
    prefix:   /

photo_admin:
    resource: "@PhotoBundle/Resources/config/routing/admin.yml"
    prefix:   /admin/